{% set name = "qcengine" %}
{% set version = "0.33.0" %}
{% set sha256 = "52d7bca6e3b6a9cebbf6db598334119d53bc3ae066627a8b4f7cbb7da1e94600" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - packaging
    - pydantic >=1.8.2
    - pyyaml
    - py-cpuinfo
    - psutil
    - qcelemental >=0.26.0,<0.70.0

test:
  imports:
    - qcengine
  requires:
    - pytest
    - msgpack-python
    - pip
    - python {{ python_min }}
    - psi4
  commands:
    - test -f $SP_DIR/qcengine/__init__.py
    # - pip check  # needed until kill off poetry in qcel as py39/numpy/pypi conflicts present
    # CORRECT but qcng adds a v for now: - python -c "import qcengine as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    - python -c "import qcengine as qc;assert qc.__version__ == 'v{{ version }}', f'{qc.__version__=} differs from recipe=\'v{{ version }}\''"
    - python -c "import importlib.metadata as md;assert md.version('{{ name }}') == '{{ version }}', f'''{md.version('{{ name }}')=} differs from recipe=\'{{ version }}\''''"
    - pytest --pyargs qcengine    

about:
  home: http://github.com/MolSSI/QCEngine
  doc_url: https://molssi.github.io/QCEngine/
  dev_url: http://github.com/MolSSI/QCEngine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A wrapper for Quantum Chemistry engines that adheres to the MolSSI (molssi.org) QCSchema.

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
    - bennybp
    - loriab
