{% set name = "qcengine" %}
{% set version = "0.31.0" %}
{% set sha256 = "51775d98239b0b51f81904f57946445970f05a0d9d139c5a89b56af9300c1e4f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - setuptools
    - pydantic >=1.8.2
    - pyyaml
    - py-cpuinfo
    - psutil
    - qcelemental >=0.26.0,<0.70.0

test:
  imports:
    - qcengine
  requires:
    - pytest
    - msgpack-python
    - pip
  commands:
    - test -f $SP_DIR/qcengine/__init__.py
    - pip check
    - python -c "import qcengine as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    - pytest --pyargs qcengine    

about:
  home: http://github.com/MolSSI/QCEngine
  doc_url: https://molssi.github.io/QCEngine/
  dev_url: http://github.com/MolSSI/QCEngine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A wrapper for Quantum Chemistry engines that adheres to the MolSSI (molssi.org) QCSchema.

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
    - bennybp
    - loriab
