{% set name = "qcengine" %}
{% set version = "0.30.0" %}
{% set sha256 = "ba62d34dbcf487e8368f6c19762a19e1c5f06af7e705f6c583c0632b35bccf7d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - pydantic >=1.8.2
    - pyyaml
    - py-cpuinfo
    - psutil
    - qcelemental >=0.26.0,<0.30.0

test:
  imports:
    - qcengine
  requires:
    - pytest
    - msgpack-python
    - python {{ python_min }}
  commands:
    - pytest --pyargs qcengine

about:
  home: http://github.com/MolSSI/QCEngine
  doc_url: https://molssi.github.io/QCEngine/
  dev_url: http://github.com/MolSSI/QCEngine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A wrapper for Quantum Chemistry engines that adheres to the MolSSI (molssi.org) QCSchema.

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
    - bennybp
    - loriab
