{% set name = "qcengine" %}
{% set version = "0.32.0" %}
{% set sha256 = "1efbd66a4edad9d8c5eb00c9687b0196d686d5d4c66ca1fbc23b2780ef9f8765" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - packaging
    - pydantic >=1.8.2
    - pyyaml
    - py-cpuinfo
    - psutil
    - qcelemental >=0.26.0,<0.70.0

test:
  imports:
    - qcengine
  requires:
    - pytest
    - msgpack-python
    - pip
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/qcengine/__init__.py
    - pip check
    # CORRECT but qcng adds a v for now: - python -c "import qcengine as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    - python -c "import qcengine as qc;assert qc.__version__ == 'v{{ version }}', f'{qc.__version__=} differs from recipe=\'v{{ version }}\''"
    - python -c "import importlib.metadata as md;assert md.version('{{ name }}') == '{{ version }}', f'''{md.version('{{ name }}')=} differs from recipe=\'{{ version }}\''''"
    - pytest --pyargs qcengine    

about:
  home: http://github.com/MolSSI/QCEngine
  doc_url: https://molssi.github.io/QCEngine/
  dev_url: http://github.com/MolSSI/QCEngine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A wrapper for Quantum Chemistry engines that adheres to the MolSSI (molssi.org) QCSchema.

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
    - bennybp
    - loriab
