{% set name = "qcengine" %}
{% set version = "0.6.3" %}
{% set sha256 = "ee08d8376639ffb035a0c30ce5dbe53cc7494779f512488a0cfcb30e6b281689" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vvv"

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pydantic >=0.20.*
    - pyyaml
    - py-cpuinfo
    - psutil
    - qcelemental >=0.3.*

test:
  imports:
    - qcengine
  requires:
    - pytest
  commands:
    - pytest --pyargs qcengine

about:
  home: http://github.com/MolSSI/QCEngine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A wrapper for Quantum Chemistry engines that adheres to the MolSSI (molssi.org) QCSchema.'

  doc_url: https://qcengine.readthedocs.io/en/latest/
  dev_url: http://github.com/MolSSI/QCEngine

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
